apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: demo-test
spec:
  components:
    - name: oam-test
      type: webservice
      properties:
        image: oamdev/hello-world
        ports:
         - port: 8000
           expose: true
#        exposeType: LoadBalancer
        cpu: "0.5"
        memory: "512Mi"
      traits:
        - type: scaler
          properties:
            replicas: 1


#日志输出到prometheus,需要开通以下插件.
#vela addon enable kube-state-metrics
#vela addon enable node-exporter
#vela addon enable prometheus-server thanos=true serviceType=LoadBalancer storage=5G
#vela addon enable loki agent=vector serviceType=LoadBalancer storage=5G
#vela addon enable grafana storage=5G
        - type: stdout-logs
          properties:
            parser: nginx


# ingress 插件解析域名,安装命令: vela addon enable ingress-nginx
        - type: gateway
          properties:
             domain: test.demo.com
             http:
                "/": 8000


#自动扩缩容addon插件,以下是cpu到达80%,自动扩容，扩容范围1~10个pod,安装命令: vela addon enable keda ,给一定压力让pod触发： ab -n 300000 -c 200  http://test.demo.com/
        - type: keda-auto-scaler
          properties:
            minReplicaCount: 1
            maxReplicaCount: 10
            cooldownPeriod: 10
            pollingInterval: 10
            triggers:
            - type: cpu
              metricType: Utilization
              metadata:
                value: "80"


#topology部署到哪个集群,如开发集群,测试集群,生产预发布集群,生产集群等等,本demo是部署到测试集群.
  policies:
    - name: target-prod
      type: topology
      properties:
        clusters: ["local"]
        namespace: "nginx"
    - name: deploy-ha
      type: override
      properties:
        components:
          - type: webservice
            traits:
              - type: scaler
                properties:
                  replicas: 2
  workflow:
    steps:
      - name: deploy2default
        type: deploy
        properties:
          policies: ["target-prod"]
